// Loads the real country outline polygons bundled in
// public/country_boundaries.json (generated by tools/FetchCountryBoundaries.py),
// used to verify bars/guesses are actually inside the selected country and
// to draw the real boundary on the map, instead of the loose backing
// rectangles in src/lib/gameBounds.js (which still back the Overpass
// query-scoping and the elimination-zone splitting math — see
// sphericalPolygon.js).
//
// Cached at module scope since this is read from three places per game
// (BoundaryScreen on every country click, GameScreen on mount,
// globalBarSelection on game start) but the data never changes at runtime.
let _cachePromise = null

function loadAllBoundaries() {
  if (!_cachePromise) {
    _cachePromise = fetch('/country_boundaries.json').then(r => {
      if (!r.ok) throw new Error('Failed to load country boundaries')
      return r.json()
    })
  }
  return _cachePromise
}

// Returns a bare GeoJSON geometry ({type, coordinates}) for the given
// country name, or null if there's no bundled polygon for it (e.g. Europe).
export async function loadCountryBoundary(countryName) {
  const all = await loadAllBoundaries()
  return all[countryName] || null
}

// True when the given size selection has a real bundled polygon to use —
// i.e. region mode on one of the 6 real countries, not a hidden continent.
export function hasCountryPolygon(selectedMode, selectedSize) {
  return selectedMode === 'region' && selectedSize !== 'Europe'
}
